title: "Lajos Galambos - Analyst"
description: "I am a finance and investment analyst with a background in economics, passionate about portfolio management, financial analysis, and exploring alternative investments."
theme: jekyll-theme-minimal
show_downloads: false
logo: "./IMG_3785.HEIC"
favicon: "./favicon.ico"

# Custom navigation
header_pages:
  - about.md
  - investment-management.md
  - forest-escapes.md
  - blog.md

# Custom settings
include:
  - _pages
  - assets
  - images

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
